#!/bin/bash
OI_PID=$(pgrep offlineimap)
if [ -z "$OI_PID" ]; then
    # My user case: echo "%{u${PB_INDG} F${PB_MUTE}}  %{-u F-}"
    # Needs font awesome, and PB_INDG defined.
    # Alternatively, build your own text
    echo "#1 Online"
else
    # My user case: echo "%{u${PB_CYAN} F${PB_GREN}}  %{-u F-}"
    # Needs font awesome, and PB_CYAN defined.
    # Alternatively, build your own text
    echo "#2 Offline"
fi
