#!/bin/sh

case "$2" in
        up)
            sh /home/user/.config/polybar/network.sh --update
        ;;
        down)
            sh /home/user/.config/polybar/network.sh --update
        ;;
esac
